version: "3.8"

volumes:
  node_modules:
services:
  web:
    build: .
    ports:
      - "3005:3000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - IP_CRON=5 2 * * *
    volumes:
      - .:/code
      - node_modules:/code/node_modules

  redis:
    image: "redis:6-alpine"

# optional and unnecessary
#  redis-commander:
#    image: "rediscommander/redis-commander"
#    environment:
#      - REDIS_HOST=redis
#    ports:
#      - "8081:8081"
#    depends_on:
#      - redis
