version: "3.8"

volumes:
  node_modules:
  redis_data:
services:
  web:
    build: .
    ports:
      - "$WEB_LISTEN_IP:3005:3000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - IP_CRON=5 2 * * *
      - COMPRESS=1
    volumes:
      - .:/code
      - node_modules:/code/node_modules
    restart: unless-stopped

  redis:
    image: "redis:6-alpine"
    volumes:
      - redis_data:/data
    restart: unless-stopped

# optional and unnecessary
#  redis-commander:
#    image: "rediscommander/redis-commander"
#    environment:
#      - REDIS_HOST=redis
#    ports:
#      - "8081:8081"
#    depends_on:
#      - redis
# 12
